language: rust
# I need this to build glfw-rs
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - secure: d0ai0sK6NFiz+822DaAKAGcJXjC6dBFLGOjqjACcsoqDtRH85HR9IVUnwCsNVPvH05frEutD5Ebd9SzrjqPriTNnzM0iwZZBxHgiHV+SAYcL/D+qyeEAB/IYU5jZxjYgq/6fHA2VhXI56rGqBRwoXe1sLsEAaTfDmo9gVi6xhQo=  echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
before_install:
  # install a newer cmake since at this time Travis only has version 2.8.7
  - yes | sudo add-apt-repository ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
install: sudo apt-get install cmake libXxf86vm-dev libxinerama-dev libxcursor-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
