[package]
name = "sogo"
version = "0.1.0"
authors = ["Rolf Sievers <rolf.sievers@posteo.de>"]

[dependencies]
rand = "*"
nalgebra =  "0.8.2"
glfw = "0.8.*"

[dependencies.kiss3d]
# path = "../rust/kiss-fork/kiss3d/"
git = "https://github.com/roSievers/kiss3d"
